command.o: command.cc ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h commandcl.h
cmdutil.o: cmdutil.cc cmdutil.h ../../../src/core/utils.src/ddconfig.h
newcmd.o: newcmd.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h ../../../src/core/utils.src/utils.h \
 ../../../src/core/utils.src/fiocl.h newcmdcl.h
newcmdposix.o: newcmdposix.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h
cmd_exec.o: cmd_exec.cc ../../../src/core/utils.src/utils.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h cmd_execcl.h commandcl.h newcmdcl.h
cmd_get.o: cmd_get.cc ../../../src/core/utils.src/utils.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h cmd_getcl.h newcmdcl.h
cmd_set.o: cmd_set.cc ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h cmd_setcl.h newcmdcl.h
cmd_timer.o: cmd_timer.cc ../../../src/core/utils.src/utils.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h ../../../src/core/sim.src/simcl.h \
 ../../../src/core/utils.src/pobjcl.h newcmdcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/sim.src/guiobjcl.h \
 newcmdposixcl.h ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h cmd_timercl.h newcmdcl.h
cmd_bp.o: cmd_bp.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h cmd_bpcl.h newcmdcl.h
cmd_info.o: cmd_info.cc ../../../src/core/sim.src/simcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h newcmdcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/sim.src/guiobjcl.h \
 newcmdposixcl.h ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h cmd_infocl.h newcmdcl.h
cmd_show.o: cmd_show.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h ../../../src/core/utils.src/utils.h \
 ../../../src/core/utils.src/fiocl.h cmd_showcl.h newcmdcl.h
cmd_gui.o: cmd_gui.cc cmd_guicl.h newcmdcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h commandcl.h
cmd_conf.o: cmd_conf.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h cmd_confcl.h newcmdcl.h
cmd_uc.o: cmd_uc.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h ../../../src/core/utils.src/utils.h \
 ../../../src/core/utils.src/fiocl.h cmd_uccl.h newcmdcl.h
cmd_stat.o: cmd_stat.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h cmd_statcl.h newcmdcl.h
cmd_mem.o: cmd_mem.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h cmd_memcl.h newcmdcl.h
cmdpars.o: cmdpars.cc cmdlexcl.h ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h
cmdlex.o: cmdlex.cc cmdlexcl.h cmdpars.hh cmdutil.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 newcmdcl.h ../../../src/core/utils.src/optioncl.h commandcl.h newcmdcl.h \
 ../../../src/core/gui.src/guicl.h ../../../src/core/gui.src/ifcl.h \
 ../../../src/core/sim.src/guiobjcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h
