_atof.o: _atof.c ../../device/include/ctype.h \
 ../../device/include/stdlib.h ../../device/include/stdbool.h
_schar2fs.o: _schar2fs.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_sint2fs.o: _sint2fs.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_slong2fs.o: _slong2fs.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_slonglong2fs.o: _slonglong2fs.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_uchar2fs.o: _uchar2fs.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_uint2fs.o: _uint2fs.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_ulong2fs.o: _ulong2fs.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_ulonglong2fs.o: _ulonglong2fs.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fs2schar.o: _fs2schar.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fs2sint.o: _fs2sint.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fs2slong.o: _fs2slong.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fs2slonglong.o: _fs2slonglong.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fs2uchar.o: _fs2uchar.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fs2uint.o: _fs2uint.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fs2ulong.o: _fs2ulong.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fs2ulonglong.o: _fs2ulonglong.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fsadd.o: _fsadd.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/stdbool.h
_fsdiv.o: _fsdiv.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fsmul.o: _fsmul.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fssub.o: _fssub.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fseq.o: _fseq.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fslt.o: _fslt.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fsneq.o: _fsneq.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
fabsf.o: fabsf.c ../../device/include/math.h ../../device/include/errno.h
frexpf.o: frexpf.c ../../device/include/math.h \
 ../../device/include/errno.h
ldexpf.o: ldexpf.c ../../device/include/math.h \
 ../../device/include/errno.h
expf.o: expf.c ../../device/include/math.h ../../device/include/errno.h \
 ../../device/include/stdbool.h
powf.o: powf.c ../../device/include/math.h ../../device/include/errno.h
sincosf.o: sincosf.c ../../device/include/math.h \
 ../../device/include/errno.h ../../device/include/stdbool.h
sinf.o: sinf.c ../../device/include/math.h ../../device/include/stdbool.h
cosf.o: cosf.c ../../device/include/math.h ../../device/include/stdbool.h
logf.o: logf.c ../../device/include/math.h ../../device/include/errno.h
log10f.o: log10f.c ../../device/include/math.h \
 ../../device/include/errno.h
sqrtf.o: sqrtf.c ../../device/include/math.h ../../device/include/errno.h
tancotf.o: tancotf.c ../../device/include/math.h \
 ../../device/include/errno.h ../../device/include/stdbool.h
tanf.o: tanf.c ../../device/include/math.h ../../device/include/stdbool.h
cotf.o: cotf.c ../../device/include/math.h ../../device/include/errno.h \
 ../../device/include/stdbool.h
asincosf.o: asincosf.c ../../device/include/math.h \
 ../../device/include/errno.h ../../device/include/stdbool.h
asinf.o: asinf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
acosf.o: acosf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
atanf.o: atanf.c ../../device/include/math.h ../../device/include/errno.h
atan2f.o: atan2f.c ../../device/include/math.h \
 ../../device/include/errno.h
sincoshf.o: sincoshf.c ../../device/include/math.h \
 ../../device/include/errno.h ../../device/include/stdbool.h
sinhf.o: sinhf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
coshf.o: coshf.c ../../device/include/math.h \
 ../../device/include/stdbool.h
tanhf.o: tanhf.c ../../device/include/math.h ../../device/include/errno.h
floorf.o: floorf.c ../../device/include/math.h
ceilf.o: ceilf.c ../../device/include/math.h
modff.o: modff.c ../../device/include/math.h
errno.o: errno.c
isinf.o: isinf.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/math.h
isnan.o: isnan.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/math.h
_fscmp.o: _fscmp.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fsget1arg.o: _fsget1arg.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fsget2args.o: _fsget2args.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fsnormalize.o: _fsnormalize.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fsreturnval.o: _fsreturnval.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fsrshift.o: _fsrshift.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_fsswapargs.o: _fsswapargs.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_logexpf.o: _logexpf.c ../../device/include/math.h
_divsint.o: _divsint.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_divuint.o: _divuint.c ../../device/include/stdbool.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_modsint.o: _modsint.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_moduint.o: _moduint.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_mulint.o: _mulint.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/stdbit.h
_divslong.o: _divslong.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_modslong.o: _modslong.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_modulong.o: _modulong.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_divulong.o: _divulong.c ../../device/include/stdbool.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_mullong.o: _mullong.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/stdbit.h
_srulonglong.o: _srulonglong.c ../../device/include/stdint.h \
 ../../device/include/stdbit.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_srslonglong.o: _srslonglong.c ../../device/include/stdint.h \
 ../../device/include/stdbit.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_slulonglong.o: _slulonglong.c ../../device/include/stdint.h \
 ../../device/include/stdbit.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_slslonglong.o: _slslonglong.c ../../device/include/stdint.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_mullonglong.o: _mullonglong.c ../../device/include/stdint.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_divslonglong.o: _divslonglong.c ../../device/include/stdint.h \
 ../../device/include/stdbool.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_divulonglong.o: _divulonglong.c ../../device/include/stdint.h \
 ../../device/include/stdbool.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_modslonglong.o: _modslonglong.c ../../device/include/stdint.h \
 ../../device/include/stdbool.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_modulonglong.o: _modulonglong.c ../../device/include/stdint.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
call_once.o: call_once.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h
isalnum.o: isalnum.c ../../device/include/ctype.h
isalpha.o: isalpha.c ../../device/include/ctype.h
isblank.o: isblank.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/ctype.h
iscntrl.o: iscntrl.c ../../device/include/ctype.h
isdigit.o: isdigit.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/ctype.h
isgraph.o: isgraph.c ../../device/include/ctype.h
islower.o: islower.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/ctype.h
isprint.o: isprint.c ../../device/include/ctype.h
ispunct.o: ispunct.c ../../device/include/ctype.h
isspace.o: isspace.c ../../device/include/ctype.h
isupper.o: isupper.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/ctype.h
isxdigit.o: isxdigit.c ../../device/include/ctype.h
tolower.o: tolower.c ../../device/include/ctype.h
toupper.o: toupper.c ../../device/include/ctype.h
ckd_add.o: ckd_add.c ../../device/include/stdckdint.h
ckd_sub.o: ckd_sub.c ../../device/include/stdckdint.h
ckd_mul.o: ckd_mul.c ../../device/include/stdckdint.h
atoi.o: atoi.c ../../device/include/stdlib.h ../../device/include/ctype.h \
 ../../device/include/stdbool.h
atol.o: atol.c ../../device/include/stdlib.h ../../device/include/ctype.h \
 ../../device/include/stdbool.h
atoll.o: atoll.c ../../device/include/stdlib.h \
 ../../device/include/ctype.h ../../device/include/stdbool.h
strtol.o: strtol.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h ../../device/include/ctype.h \
 ../../device/include/limits.h ../../device/include/errno.h
strtoll.o: strtoll.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h ../../device/include/ctype.h \
 ../../device/include/limits.h ../../device/include/errno.h
strtoimax.o: strtoimax.c ../../device/include/inttypes.h \
 ../../device/include/stdint.h ../../device/include/stdlib.h
strtoul.o: strtoul.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h ../../device/include/ctype.h \
 ../../device/include/string.h ../../device/include/stdckdint.h \
 ../../device/include/limits.h ../../device/include/errno.h
strtoull.o: strtoull.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h ../../device/include/ctype.h \
 ../../device/include/string.h ../../device/include/limits.h \
 ../../device/include/errno.h
strtoumax.o: strtoumax.c ../../device/include/inttypes.h \
 ../../device/include/stdint.h ../../device/include/stdlib.h
wcstol.o: wcstol.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h ../../device/include/ctype.h \
 ../../device/include/limits.h ../../device/include/errno.h \
 ../../device/include/wchar.h
wcstoll.o: wcstoll.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h ../../device/include/ctype.h \
 ../../device/include/limits.h ../../device/include/errno.h \
 ../../device/include/wchar.h
wcstoimax.o: wcstoimax.c ../../device/include/inttypes.h \
 ../../device/include/stdint.h ../../device/include/wchar.h
wcstoul.o: wcstoul.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h ../../device/include/ctype.h \
 ../../device/include/string.h ../../device/include/stdckdint.h \
 ../../device/include/limits.h ../../device/include/errno.h \
 ../../device/include/wchar.h
wcstoull.o: wcstoull.c ../../device/include/stdlib.h \
 ../../device/include/stdbool.h ../../device/include/ctype.h \
 ../../device/include/string.h ../../device/include/limits.h \
 ../../device/include/errno.h ../../device/include/wchar.h
wcstoumax.o: wcstoumax.c ../../device/include/inttypes.h \
 ../../device/include/stdint.h ../../device/include/wchar.h
bsearch.o: bsearch.c ../../device/include/stdlib.h
qsort.o: qsort.c ../../device/include/stdlib.h
abs.o: abs.c ../../device/include/stdlib.h
labs.o: labs.c ../../device/include/stdlib.h
llabs.o: llabs.c
imaxabs.o: imaxabs.c ../../device/include/inttypes.h \
 ../../device/include/stdint.h
umaxabs.o: umaxabs.c ../../device/include/inttypes.h \
 ../../device/include/stdint.h
rand.o: rand.c ../../device/include/stdlib.h \
 ../../device/include/stdint.h
_strcat.o: _strcat.c ../../device/include/string.h
_strchr.o: _strchr.c ../../device/include/string.h
_strcspn.o: _strcspn.c ../../device/include/string.h
strdup.o: strdup.c ../../device/include/string.h \
 ../../device/include/stdlib.h
strndup.o: strndup.c ../../device/include/string.h \
 ../../device/include/stdlib.h
_strncat.o: _strncat.c ../../device/include/string.h
_strncmp.o: _strncmp.c ../../device/include/string.h
strxfrm.o: strxfrm.c ../../device/include/string.h
_strncpy.o: _strncpy.c ../../device/include/string.h
_strpbrk.o: _strpbrk.c ../../device/include/string.h
_strrchr.o: _strrchr.c ../../device/include/string.h
_strspn.o: _strspn.c ../../device/include/string.h
_strstr.o: _strstr.c ../../device/include/string.h
_strtok.o: _strtok.c ../../device/include/string.h
memccpy.o: memccpy.c ../../device/include/string.h
_memchr.o: _memchr.c ../../device/include/string.h
_memcmp.o: _memcmp.c ../../device/include/string.h
_memset.o: _memset.c ../../device/include/stdlib.h \
 ../../device/include/string.h
memset_explicit.o: memset_explicit.c ../../device/include/string.h
aligned_alloc.o: aligned_alloc.c ../../device/include/stddef.h \
 ../../device/include/stdlib.h
calloc.o: calloc.c ../../device/include/stdlib.h \
 ../../device/include/string.h ../../device/include/stdint.h
malloc.o: malloc.c ../../device/include/stdlib.h \
 ../../device/include/stddef.h
realloc.o: realloc.c ../../device/include/stdlib.h \
 ../../device/include/stddef.h ../../device/include/string.h
free.o: free.c ../../device/include/stdlib.h \
 ../../device/include/stddef.h
mblen.o: mblen.c ../../device/include/stdlib.h
mbtowc.o: mbtowc.c ../../device/include/stdlib.h
wctomb.o: wctomb.c ../../device/include/stdlib.h
mbstowcs.o: mbstowcs.c ../../device/include/stdlib.h \
 ../../device/include/limits.h
wcstombs.o: wcstombs.c ../../device/include/stdlib.h \
 ../../device/include/limits.h
memalignment.o: memalignment.c ../../device/include/stdlib.h \
 ../../device/include/stdint.h
mbrtoc16.o: mbrtoc16.c ../../device/include/uchar.h \
 ../../device/include/limits.h ../../device/include/wchar.h
c16rtomb.o: c16rtomb.c ../../device/include/uchar.h \
 ../../device/include/stdlib.h ../../device/include/limits.h \
 ../../device/include/errno.h
mbrtoc32.o: mbrtoc32.c ../../device/include/uchar.h \
 ../../device/include/limits.h ../../device/include/wchar.h
c32rtomb.o: c32rtomb.c ../../device/include/uchar.h \
 ../../device/include/stdlib.h
mbstoc16s.o: mbstoc16s.c ../../device/include/uchar.h \
 ../../device/include/stdlib.h ../../device/include/limits.h \
 ../../device/include/wchar.h
c16stombs.o: c16stombs.c ../../device/include/uchar.h \
 ../../device/include/stdlib.h ../../device/include/string.h \
 ../../device/include/limits.h ../../device/include/wchar.h
wcscmp.o: wcscmp.c ../../device/include/wchar.h
wcslen.o: wcslen.c ../../device/include/wchar.h
wcsncmp.o: wcsncmp.c ../../device/include/wchar.h
wcsnlen.o: wcsnlen.c ../../device/include/wchar.h
btowc.o: btowc.c ../../device/include/wchar.h \
 ../../device/include/stdio.h ../../device/include/stdarg.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
wctob.o: wctob.c ../../device/include/wchar.h \
 ../../device/include/stdio.h ../../device/include/stdarg.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
mbsinit.o: mbsinit.c ../../device/include/wchar.h
mbrlen.o: mbrlen.c ../../device/include/wchar.h
mbrtowc.o: mbrtowc.c ../../device/include/wchar.h \
 ../../device/include/errno.h
wcrtomb.o: wcrtomb.c ../../device/include/wchar.h \
 ../../device/include/stdlib.h ../../device/include/errno.h
printf_large.o: printf_large.c ../../device/include/stdarg.h \
 ../../device/include/string.h ../../device/include/ctype.h \
 ../../device/include/stdio.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/stdbit.h
puts.o: puts.c ../../device/include/stdio.h ../../device/include/stdarg.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
gets.o: gets.c ../../device/include/stdio.h ../../device/include/stdarg.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
__assert.o: __assert.c ../../device/include/stdio.h \
 ../../device/include/stdarg.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/stdlib.h
time.o: time.c ../../device/include/stdio.h ../../device/include/stdarg.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h ../../device/include/time.h
__stdc_leading_zeros.o: __stdc_leading_zeros.c \
 ../../device/include/stdbit.h ../../device/include/limits.h \
 ../../device/include/stdint.h
__stdc_trailing_ones.o: __stdc_trailing_ones.c \
 ../../device/include/stdbit.h ../../device/include/limits.h \
 ../../device/include/stdint.h ../../device/include/assert.h
__stdc_first_leading_one.o: __stdc_first_leading_one.c \
 ../../device/include/stdbit.h ../../device/include/limits.h \
 ../../device/include/stdint.h
__stdc_first_trailing_one.o: __stdc_first_trailing_one.c \
 ../../device/include/stdbit.h ../../device/include/limits.h \
 ../../device/include/stdint.h
__stdc_count_ones.o: __stdc_count_ones.c ../../device/include/stdbit.h \
 ../../device/include/limits.h ../../device/include/stdint.h \
 ../../device/include/assert.h
__stdc_bit_width.o: __stdc_bit_width.c ../../device/include/stdbit.h \
 ../../device/include/limits.h ../../device/include/stdint.h \
 ../../device/include/assert.h
__stdc_bit_ceilull.o: __stdc_bit_ceilull.c ../../device/include/stdbit.h \
 ../../device/include/limits.h ../../device/include/stdint.h \
 ../../device/include/assert.h
stdc_memreverse8.o: stdc_memreverse8.c ../../device/include/stdbit.h
stdc_memreverse8u.o: stdc_memreverse8u.c ../../device/include/stdint.h \
 ../../device/include/stdbit.h
stdc_load8.o: stdc_load8.c ../../device/include/stdint.h \
 ../../device/include/stdbit.h
stdc_store8.o: stdc_store8.c ../../device/include/stdint.h \
 ../../device/include/stdbit.h
_autobaud.o: _autobaud.c ../../device/include/mcs51/8051.h
_bp.o: _bp.c
_decdptr.o: _decdptr.c
_gptrget.o: _gptrget.c
_gptrgetc.o: _gptrgetc.c
_gptrput.o: _gptrput.c
_ser.o: _ser.c ../../device/include/mcs51/8052.h \
 ../../device/include/mcs51/8051.h ../../device/include/mcs51/ser.h
_setjmp.o: _setjmp.c ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/setjmp.h ../../device/include/mcs51/8051.h
serial.o: serial.c ../../device/include/mcs51/8052.h \
 ../../device/include/mcs51/8051.h
__itoa.o: __itoa.c ../../device/include/stdlib.h
__ltoa.o: __ltoa.c ../../device/include/stdlib.h
_spx.o: _spx.c
_startup.o: _startup.c
_strcmp.o: _strcmp.c ../../device/include/string.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
strlen.o: strlen.c ../../device/include/string.h
strnlen.o: strnlen.c ../../device/include/string.h
__memcpy.o: __memcpy.c ../../device/include/string.h
memcpy.o: memcpy.c ../../device/include/string.h
_memmove.o: _memmove.c ../../device/include/string.h \
 ../../device/include/stdint.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_strcpy.o: _strcpy.c ../../device/include/string.h \
 ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
_heap.o: _heap.c
div.o: div.c ../../device/include/stdlib.h
ldiv.o: ldiv.c ../../device/include/stdlib.h
lldiv.o: lldiv.c ../../device/include/stdlib.h
imaxdiv.o: imaxdiv.c ../../device/include/inttypes.h \
 ../../device/include/stdint.h
sprintf.o: sprintf.c ../../device/include/stdarg.h \
 ../../device/include/stdio.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
vprintf.o: vprintf.c ../../device/include/stdarg.h \
 ../../device/include/stdio.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
printf_fast.o: printf_fast.c
printf_fast_f.o: printf_fast_f.c ../../device/include/float.h \
 ../../device/include/limits.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h
printf_tiny.o: printf_tiny.c
printfl.o: printfl.c ../../device/include/stdarg.h \
 ../../device/include/stdio.h ../../device/include/sdcc-lib.h \
 ../../device/include/asm/default/features.h \
 ../../device/include/stdlib.h
bpx.o: bpx.c
