#
# uCsim  simulator Makefile
#
# (c) Drotos Daniel, Talker Bt. 1997
#

srcdir          = .

top_builddir	= ../../..
top_srcdir	= ../../..

include $(srcdir)/objs.mk
include ../../common.mk


# Compiling entire program or any subproject
# ------------------------------------------
all: $(UCSIM_LIB_TARGETS) $(LEN)

include $(top_srcdir)/src/app.mk

local_install:

local_uninstall:


# End of simulator Makefile
