pobj.o: pobj.cc pstr.h ddconfig.h pobjcl.h pobjt.h eventcl.h charscl.h
globals.o: globals.cc stypes.h ddconfig.h
utils.o: utils.cc ddconfig.h stypes.h globals.h appcl.h pobjcl.h pobjt.h \
 eventcl.h charscl.h optioncl.h ../../../src/core/sim.src/argcl.h \
 pobjcl.h stypes.h ../../../src/core/sim.src/simcl.h \
 ../../../src/core/cmd.src/newcmdcl.h ddconfig.h optioncl.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h ../../../src/core/gui.src/guicl.h \
 ../../../src/core/gui.src/ifcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/sim.src/uccl.h pobjt.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h fiocl.h charscl.h pobjcl.h \
 ../../../src/core/cmd.src/cmdutil.h ../../../src/core/sim.src/memcl.h \
 eventcl.h errorcl.h stypes.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h utils.h fiocl.h
error.o: error.cc i_string.h ddconfig.h errorcl.h pobjcl.h pobjt.h \
 eventcl.h charscl.h stypes.h globals.h appcl.h optioncl.h \
 ../../../src/core/sim.src/argcl.h pobjcl.h stypes.h \
 ../../../src/core/sim.src/simcl.h ../../../src/core/cmd.src/newcmdcl.h \
 ddconfig.h optioncl.h ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h ../../../src/core/gui.src/guicl.h \
 ../../../src/core/gui.src/ifcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/sim.src/uccl.h pobjt.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h fiocl.h charscl.h pobjcl.h \
 ../../../src/core/cmd.src/cmdutil.h ../../../src/core/sim.src/memcl.h \
 eventcl.h errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h utils.h fiocl.h
app.o: app.cc ddconfig.h i_string.h utils.h stypes.h charscl.h fiocl.h \
 pobjcl.h pobjt.h eventcl.h appcl.h optioncl.h \
 ../../../src/core/sim.src/argcl.h pobjcl.h stypes.h \
 ../../../src/core/sim.src/simcl.h ../../../src/core/cmd.src/newcmdcl.h \
 ddconfig.h optioncl.h ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h ../../../src/core/gui.src/guicl.h \
 ../../../src/core/gui.src/ifcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/sim.src/uccl.h pobjt.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h fiocl.h \
 ../../../src/core/cmd.src/cmdutil.h ../../../src/core/sim.src/memcl.h \
 eventcl.h errorcl.h pobjcl.h stypes.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h globals.h \
 ../../../src/core/cmd.src/cmd_execcl.h \
 ../../../src/core/cmd.src/cmdutil.h \
 ../../../src/core/cmd.src/cmd_confcl.h \
 ../../../src/core/cmd.src/cmd_showcl.h \
 ../../../src/core/cmd.src/cmd_getcl.h \
 ../../../src/core/cmd.src/cmd_setcl.h \
 ../../../src/core/cmd.src/cmdlexcl.h
option.o: option.cc ddconfig.h i_string.h stypes.h optioncl.h pobjcl.h \
 pobjt.h eventcl.h charscl.h globals.h appcl.h \
 ../../../src/core/sim.src/argcl.h pobjcl.h stypes.h \
 ../../../src/core/sim.src/simcl.h ../../../src/core/cmd.src/newcmdcl.h \
 ddconfig.h optioncl.h ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h ../../../src/core/gui.src/guicl.h \
 ../../../src/core/gui.src/ifcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/sim.src/uccl.h pobjt.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h fiocl.h charscl.h pobjcl.h \
 ../../../src/core/cmd.src/cmdutil.h ../../../src/core/sim.src/memcl.h \
 eventcl.h errorcl.h stypes.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h utils.h fiocl.h
chars.o: chars.cc charscl.h
fio.o: fio.cc ddconfig.h fiocl.h charscl.h pobjcl.h pobjt.h eventcl.h \
 utils.h stypes.h
fuio.o: fuio.cc ddconfig.h utils.h stypes.h charscl.h fiocl.h pobjcl.h \
 pobjt.h eventcl.h fuiocl.h
